### ISSUE TITLE
Chybějící úvozovky pro celou citaci

### ISSUE THREAD

**Issue by liskajiri** [ufal/media-irozhlas#16]
V záznamu `"id": "6674847"` chybí pro některé citace začáteční (viz. také #15) a koncové úvozovky.
Např.
`„Nemá s tím problém. Naopak sám říká, že je tohle potřeba udělat,“ dodala Jana.`
se transformuje na:
`Nem\u00e1 s t\u00edm probl\u00e9m. Naopak s\u00e1m \u0159\u00edk\u00e1, \u017ee je tohle pot\u0159eba ud\u011blat,\u201c dodala Jana.`

Pravděpodobně souvisí s #15

**Comment by matyaskopp** [comment]
ano, souvisí s #15
