### ISSUE TITLE
TEITOK: Annotation level 

### ISSUE THREAD

**Issue by hladkab** [ufal/media-irozhlas#23]
Navrhuji Annotation level přejmenovat na Annotation quality a Kvalita anotací.

Co kdybychom pro vizualizaci kvality použili hvězdičkový systém? Čím víc hvězdiček, tím lépe a  
- [#double_unified] dvě hvězdičky **
- [#triple_unified_curated] tři hvězdičky ***

**Comment by matyaskopp** [comment]
>Navrhuji Annotation level přejmenovat na Annotation quality a Kvalita anotací.

@hladkab,
ok
nyní se v dotazu filtruje typ anotace pomocí `match.text_annotation_level = "#double_unified"`
tak `annotation_level` změním na `aquality`, když v ostatních případech používám `atype`, `asource` a `asignal`

> Co kdybychom pro vizualizaci kvality použili hvězdičkový systém? Čím víc hvězdiček, tím lépe a
- [#double_unified] dvě hvězdičky **
- [#triple_unified_curated] tři hvězdičky ***

hvězdička je špatný znak vzhledem k regulárním výrazům, dotazovat by se muselo pomocí hodnot `\*\*` a `\*\*\*`

**Comment by hladkab** [comment]
A jaký znak by šel?  x ?

**Comment by matyaskopp** [comment]
data jsou nahraná v TEITOKu
