### ISSUE TITLE
TEITOK: hlavička dokumentů

### ISSUE THREAD

**Issue by hladkab** [ufal/media-irozhlas#25]
![hlavicka](https://user-images.githubusercontent.com/50826139/189105515-5c7dd2f0-3147-4d4c-aa9a-f4f318eec837.PNG)

Co znamená MWEs and links View? Musí tam být [view teiHeader]?

**Comment by matyaskopp** [comment]
> MWEs and links View

je typ modulu, který používám pro zobrazení. Mohu odstranit.

> [view teiHeader]

view teiHeader vidíte pouze po přihlášení. Ostatní uživatelé nevidí

**Comment by hladkab** [comment]
Nechat MWEs and links View pro admin, pro ostatní skrýt?

**Comment by hladkab** [comment]
Dobře, skryjte.

**Comment by matyaskopp** [comment]
nechám si issue otevřené, ať na to nezapomenu

**Comment by matyaskopp** [comment]
upravil jsem jméno zobrazení v nastavení. Typ anotace který je aktuálně zobrazený bych tam nechal (text/překlad můžu upravit)

![image](https://user-images.githubusercontent.com/5867995/190109126-8bfb4d91-7252-4715-bd80-054eae475301.png)
