### ISSUE TITLE
TEITOK: filtrování podle Annotation level

### ISSUE THREAD

**Issue by hladkab** [ufal/media-irozhlas#27]
![czen](https://user-images.githubusercontent.com/50826139/189106403-ea49109d-b177-490f-90de-3d6b19146d17.PNG)
Šlo by v Annotation level dát možnost výběru?

**Comment by matyaskopp** [comment]
V "Document Browse" se zobrazují dokumenty pouze podle jedné vlastnosti (v tomto případě `author`)

Zobrazený výšet dokumentů je shodný s výsledkem dotazu
```CQL
<text> [] :: match.text_author = "(.*,)?(Adam Weidenthaler)(,.*)?"
```

**Comment by matyaskopp** [comment]
> Šlo by v Annotation level dát možnost výběru?

nešlo
