### ISSUE TITLE
TEITOK: nefunguje tlačítko Další

### ISSUE THREAD

**Issue by hladkab** [ufal/media-irozhlas#28]
![dalsi](https://user-images.githubusercontent.com/50826139/190112944-c79102f2-7628-41ae-aeec-627dab36908b.PNG)

**Comment by matyaskopp** [comment]
dočasně vyřešeno přepnutím z tabulkového zobrazení na standartní:
```XML
<ttssettings>
        <defaults>
            <!--browser style="table"/-->
        </defaults>
</ttsettings>
```

**Comment by matyaskopp** [comment]
opraveno
![image](https://user-images.githubusercontent.com/5867995/190589777-6db15a95-a1a4-44eb-9a02-f408898d7ac9.png)
